@extends('layouts.app')

@section('title', 'Kalender Kegiatan RT')

@section('content')
<link rel="stylesheet" href="{{ asset('css/kalender.css') }}">

<div class="kalender-container">
    <!-- Header Section -->
    <div class="page-header">
        <div class="header-content">
            <h1>📅 Kalender Kegiatan RT</h1>
            <p>Jadwal dan agenda kegiatan RT untuk bulan ini</p>
        </div>
        <div class="header-actions">
            <a href="{{ route('kalender.create') }}" class="btn-primary">
                <i class="icon">➕</i>
                Tambah Kegiatan
            </a>
        </div>
    </div>

    <!-- Calendar Navigation -->
    <div class="calendar-nav">
        <div class="nav-controls">
            <button class="nav-btn" onclick="previousMonth()">
                <i class="icon">◀</i>
            </button>
            <div class="current-month">
                <h2 id="currentMonth">{{ date('F Y') }}</h2>
            </div>
            <button class="nav-btn" onclick="nextMonth()">
                <i class="icon">▶</i>
            </button>
        </div>
        <div class="view-toggle">
            <button class="toggle-btn active" onclick="switchView('calendar')">Kalender</button>
            <button class="toggle-btn" onclick="switchView('list')">Daftar</button>
        </div>
    </div>

    <!-- Calendar View -->
    <div id="calendarView" class="calendar-view">
        <div class="calendar-grid">
            <!-- Calendar Header -->
            <div class="calendar-header">
                <div class="day-header">Min</div>
                <div class="day-header">Sen</div>
                <div class="day-header">Sel</div>
                <div class="day-header">Rab</div>
                <div class="day-header">Kam</div>
                <div class="day-header">Jum</div>
                <div class="day-header">Sab</div>
            </div>
            
            <!-- Calendar Body -->
            <div class="calendar-body" id="calendarDays">
                <!-- Calendar days will be generated by JavaScript -->
            </div>
        </div>
    </div>

    <!-- List View -->
    <div id="listView" class="list-view" style="display: none;">
        <div class="events-list">
            <!-- Upcoming Events -->
            <div class="events-section">
                <h3>Kegiatan Mendatang</h3>
                <div class="event-items">
                    @forelse($upcomingEvents ?? [] as $event)
                    <div class="event-card">
                        <div class="event-date-badge">
                            <div class="date-day">{{ date('d', strtotime($event->event_date)) }}</div>
                            <div class="date-month">{{ date('M', strtotime($event->event_date)) }}</div>
                        </div>
                        <div class="event-details">
                            <h4>{{ $event->title }}</h4>
                            <p class="event-description">{{ $event->description }}</p>
                            <div class="event-meta">
                                <span class="event-time">
                                    <i class="icon">🕐</i>
                                    {{ date('H:i', strtotime($event->start_time)) }} - {{ date('H:i', strtotime($event->end_time)) }}
                                </span>
                                <span class="event-location">
                                    <i class="icon">📍</i>
                                    {{ $event->location }}
                                </span>
                            </div>
                        </div>
                        <div class="event-actions">
                            <a href="{{ route('kalender.show', $event->id) }}" class="btn-view">Detail</a>
                            @if(auth()->user()->role === 'admin' || $event->created_by === auth()->id())
                            <a href="{{ route('kalender.edit', $event->id) }}" class="btn-edit">Edit</a>
                            @endif
                        </div>
                    </div>
                    @empty
                    <div class="empty-state">
                        <p>Belum ada kegiatan yang dijadwalkan</p>
                    </div>
                    @endforelse
                </div>
            </div>

            <!-- Past Events -->
            <div class="events-section">
                <h3>Kegiatan Sebelumnya</h3>
                <div class="event-items">
                    @forelse($pastEvents ?? [] as $event)
                    <div class="event-card past-event">
                        <div class="event-date-badge past">
                            <div class="date-day">{{ date('d', strtotime($event->event_date)) }}</div>
                            <div class="date-month">{{ date('M', strtotime($event->event_date)) }}</div>
                        </div>
                        <div class="event-details">
                            <h4>{{ $event->title }}</h4>
                            <p class="event-description">{{ $event->description }}</p>
                            <div class="event-meta">
                                <span class="event-time">
                                    <i class="icon">🕐</i>
                                    {{ date('H:i', strtotime($event->start_time)) }} - {{ date('H:i', strtotime($event->end_time)) }}
                                </span>
                                <span class="event-location">
                                    <i class="icon">📍</i>
                                    {{ $event->location }}
                                </span>
                            </div>
                        </div>
                        <div class="event-actions">
                            <a href="{{ route('kalender.show', $event->id) }}" class="btn-view">Detail</a>
                        </div>
                    </div>
                    @empty
                    <div class="empty-state">
                        <p>Belum ada riwayat kegiatan</p>
                    </div>
                    @endforelse
                </div>
            </div>
        </div>
    </div>

    <!-- Quick Stats -->
    <div class="quick-stats">
        <div class="stat-item">
            <div class="stat-icon">📅</div>
            <div class="stat-content">
                <h4>{{ $totalEvents ?? 0 }}</h4>
                <p>Total Kegiatan</p>
            </div>
        </div>
        <div class="stat-item">
            <div class="stat-icon">⏰</div>
            <div class="stat-content">
                <h4>{{ $upcomingCount ?? 0 }}</h4>
                <p>Kegiatan Mendatang</p>
            </div>
        </div>
        <div class="stat-item">
            <div class="stat-icon">✅</div>
            <div class="stat-content">
                <h4>{{ $completedCount ?? 0 }}</h4>
                <p>Kegiatan Selesai</p>
            </div>
        </div>
        <div class="stat-item">
            <div class="stat-icon">👥</div>
            <div class="stat-content">
                <h4>{{ $totalParticipants ?? 0 }}</h4>
                <p>Total Peserta</p>
            </div>
        </div>
    </div>
</div>

<!-- Event Detail Modal -->
<div id="eventModal" class="modal" style="display: none;">
    <div class="modal-content">
        <div class="modal-header">
            <h3 id="modalTitle">Detail Kegiatan</h3>
            <button class="modal-close" onclick="closeModal()">&times;</button>
        </div>
        <div class="modal-body" id="modalBody">
            <!-- Event details will be loaded here -->
        </div>
    </div>
</div>

<script>
// Sample events data - replace with actual data from backend
const events = @json($events ?? []);
let currentDate = new Date();
let currentView = 'calendar';

// Initialize calendar
document.addEventListener('DOMContentLoaded', function() {
    generateCalendar();
});

function generateCalendar() {
    const year = currentDate.getFullYear();
    const month = currentDate.getMonth();
    
    // Update month display
    document.getElementById('currentMonth').textContent = 
        new Date(year, month).toLocaleDateString('id-ID', { month: 'long', year: 'numeric' });
    
    // Get first day of month and number of days
    const firstDay = new Date(year, month, 1).getDay();
    const daysInMonth = new Date(year, month + 1, 0).getDate();
    
    const calendarDays = document.getElementById('calendarDays');
    calendarDays.innerHTML = '';
    
    // Add empty cells for days before month starts
    for (let i = 0; i < firstDay; i++) {
        const emptyDay = document.createElement('div');
        emptyDay.className = 'calendar-day empty';
        calendarDays.appendChild(emptyDay);
    }
    
    // Add days of the month
    for (let day = 1; day <= daysInMonth; day++) {
        const dayElement = document.createElement('div');
        dayElement.className = 'calendar-day';
        
        const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        const dayEvents = events.filter(event => event.event_date === dateStr);
        
        // Check if today
        const today = new Date();
        if (year === today.getFullYear() && month === today.getMonth() && day === today.getDate()) {
            dayElement.classList.add('today');
        }
        
        dayElement.innerHTML = `
            <div class="day-number">${day}</div>
            ${dayEvents.length > 0 ? `<div class="event-indicator">${dayEvents.length}</div>` : ''}
        `;
        
        if (dayEvents.length > 0) {
            dayElement.classList.add('has-events');
            dayElement.addEventListener('click', () => showDayEvents(dateStr, dayEvents));
        }
        
        calendarDays.appendChild(dayElement);
    }
}

function previousMonth() {
    currentDate.setMonth(currentDate.getMonth() - 1);
    generateCalendar();
}

function nextMonth() {
    currentDate.setMonth(currentDate.getMonth() + 1);
    generateCalendar();
}

function switchView(view) {
    const calendarView = document.getElementById('calendarView');
    const listView = document.getElementById('listView');
    const toggleBtns = document.querySelectorAll('.toggle-btn');
    
    toggleBtns.forEach(btn => btn.classList.remove('active'));
    
    if (view === 'calendar') {
        calendarView.style.display = 'block';
        listView.style.display = 'none';
        toggleBtns[0].classList.add('active');
    } else {
        calendarView.style.display = 'none';
        listView.style.display = 'block';
        toggleBtns[1].classList.add('active');
    }
    
    currentView = view;
}

function showDayEvents(date, dayEvents) {
    const modal = document.getElementById('eventModal');
    const modalTitle = document.getElementById('modalTitle');
    const modalBody = document.getElementById('modalBody');
    
    modalTitle.textContent = `Kegiatan ${new Date(date).toLocaleDateString('id-ID', { 
        day: 'numeric', 
        month: 'long', 
        year: 'numeric' 
    })}`;
    
    modalBody.innerHTML = dayEvents.map(event => `
        <div class="modal-event">
            <h4>${event.title}</h4>
            <p>${event.description}</p>
            <div class="modal-event-meta">
                <span><i class="icon">🕐</i> ${event.start_time} - ${event.end_time}</span>
                <span><i class="icon">📍</i> ${event.location}</span>
            </div>
        </div>
    `).join('');
    
    modal.style.display = 'flex';
}

function closeModal() {
    document.getElementById('eventModal').style.display = 'none';
}

// Close modal when clicking outside
window.onclick = function(event) {
    const modal = document.getElementById('eventModal');
    if (event.target === modal) {
        modal.style.display = 'none';
    }
}
</script>
@endsection